In [15]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets, svm, metrics

In [16]:
from sklearn.datasets import load_digits
digits = load_digits()
train = digits.data
targets = digits.target

In [17]:
from sklearn.cluster import AgglomerativeClustering

ac = AgglomerativeClustering(n_clusters=10)
pred = ac.fit(train)

In [18]:
# print(targets)
Labels = pred.labels_
print(Labels)

[7 9 4 ... 4 1 4]


In [19]:
def clusterChecking(tar,lab):
    new_lab=np.copy(lab)
    for j in range(10):
        temp=np.where(lab==j)
        temp_array=tar[temp]
        vals,counts = np.unique(temp_array, return_counts=True)
       
        index = np.argmax(counts)
        m=vals[index]
        new_lab[temp]=m
    return new_lab  

In [20]:
new = clusterChecking(targets, Labels)
# print(targets)
print(Labels)
print(new)

[7 9 4 ... 4 1 4]
[0 1 8 ... 8 3 8]


In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(targets, new)
print(cm)

[[178   0   0   0   0   0   0   0   0   0]
 [  0 155  27   0   0   0   0   0   0   0]
 [  0   0 166   0   0   0   0   1  10   0]
 [  0   0   0 169   0   0   0   1  13   0]
 [  0   0   0   0 178   0   0   3   0   0]
 [  0   0   0   2   0 179   1   0   0   0]
 [  0   0   0   0   0   0 180   0   1   0]
 [  0   0   0   0   0   0   0 179   0   0]
 [  0   3   4   1   0   0   0   1 165   0]
 [  0  20   0 145   0   2   0  11   2   0]]


In [22]:
accuracy = metrics.fowlkes_mallows_score(targets, new)
print('Accuracy: ',accuracy*100, '%')

Accuracy:  83.21395046705491 %
